/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bài69.bài80;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author ADMIN
 */
public class Bai86 extends javax.swing.JFrame {

    /**
     * Creates new form Bai86
     */
    public Bai86() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btntodensochan = new javax.swing.JButton();
        btntodensole = new javax.swing.JButton();
        btntodensonguyento = new javax.swing.JButton();
        btnbotoden = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnnhap = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(498, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Thao tác trên Jlist và CheckBox");

        btntodensochan.setText("Tô đen số chắn");
        btntodensochan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodensochanActionPerformed(evt);
            }
        });

        btntodensole.setText("Tô đen số lẻ");
        btntodensole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodensoleActionPerformed(evt);
            }
        });

        btntodensonguyento.setText("Tô đen số nguyên tố");
        btntodensonguyento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodensonguyentoActionPerformed(evt);
            }
        });

        btnbotoden.setText("Bỏ tô đen");
        btnbotoden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbotodenActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa các giá trị đang tô đen");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntong.setText("Tổng giá trị trong JList");
        btntong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntodensochan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntodensonguyento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntodensole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbotoden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntodensochan)
                .addGap(18, 18, 18)
                .addComponent(btntodensole)
                .addGap(18, 18, 18)
                .addComponent(btntodensonguyento)
                .addGap(18, 18, 18)
                .addComponent(btnbotoden)
                .addGap(18, 18, 18)
                .addComponent(btnxoa)
                .addGap(18, 18, 18)
                .addComponent(btntong)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnnhap.setText("Nhập");
        btnnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Cho phép số âm");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnnhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnhap)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jButton1.setText("Thoát chương trình");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel model= new DefaultListModel();
    public boolean ktranguyento(int a)
    {
    if (a < 2)    
        return true;

    for (int i = 2; i <= Math.sqrt(a); i ++)
    {
        if (a%i==0)
        {
            return false;
        }
    }
    return true;
}
    private void btnnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
            model.addElement(Integer.valueOf(jTextField1.getText()));
        else if(Integer.parseInt(jTextField1.getText())<0)
            JOptionPane.showMessageDialog(this,"Phải nhập số dương");
        else model.addElement(Integer.valueOf(jTextField1.getText()));
        jList1.setModel(model);
    }//GEN-LAST:event_btnnhapActionPerformed

    private void btntodensochanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodensochanActionPerformed
        // TODO add your handling code here:
      int[] b=new int[model.size()];
      for(int i =0;i<model.getSize();i++)
      {
          String s=String.valueOf(model.getElementAt(i));
          if((Integer.valueOf(s)%2)==0)
          {
              b[i]=i;
             // jList1.setSelectedIndex(i);
          }
          else b[i]=-1;
      }
           jList1.setSelectedIndices(b);
    }//GEN-LAST:event_btntodensochanActionPerformed

    private void btntodensoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodensoleActionPerformed
        // TODO add your handling code here:
         int[] b=new int[model.size()];
      for(int i =0;i<model.getSize();i++)
      {
          String s=String.valueOf(model.getElementAt(i));
          if((Integer.valueOf(s)%2)!=0)
          {
              b[i]=i;
             // jList1.setSelectedIndex(i);
          }
          else b[i]=-1;
      }
           jList1.setSelectedIndices(b);
    }//GEN-LAST:event_btntodensoleActionPerformed

    private void btntodensonguyentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodensonguyentoActionPerformed
        // TODO add your handling code here:
          int[] b=new int[model.size()];
      for(int i =0;i<model.getSize();i++)
      {
          String s=String.valueOf(model.getElementAt(i));
          if(ktranguyento(Integer.valueOf(s)))
          {
              b[i]=i;
             // jList1.setSelectedIndex(i);
          }
          else b[i]=-1;
      }
           jList1.setSelectedIndices(b);
    }//GEN-LAST:event_btntodensonguyentoActionPerformed

    private void btnbotodenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbotodenActionPerformed
        // TODO add your handling code here:
        jList1.clearSelection();
    }//GEN-LAST:event_btnbotodenActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int[] index=jList1.getSelectedIndices();
        for(int i=index.length-1;i>=0;i--)
            model.remove(index[i]);
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongActionPerformed
        // TODO add your handling code here:
        int s=0;
        for(int i=0;i<model.size();i++)
        {
            String a= String.valueOf(model.get(i));
            s=s+Integer.valueOf(a);
        }
        JOptionPane.showMessageDialog(this,"Tổng giá trị trong List là :"+s);
    }//GEN-LAST:event_btntongActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(this, "Ban chắc chắc muốn thoát?","Thông báo",JOptionPane.OK_CANCEL_OPTION);
        if(n==JOptionPane.OK_OPTION)
            System.exit(n);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     */
public void veborderpenal1()
    {
        Border mauBorder=BorderFactory.createLineBorder(Color.red);
        TitledBorder vienBorder= BorderFactory.createTitledBorder(mauBorder,"Chọn tác vụ");
        vienBorder.setTitleJustification(TitledBorder.LEFT);
        jPanel1.setBorder(vienBorder);
    }
public void veborderpenal2()
    {
        Border mauBorder=BorderFactory.createLineBorder(Color.red);
        TitledBorder vienBorder= BorderFactory.createTitledBorder(mauBorder,"Nhập thông tin");
        vienBorder.setTitleJustification(TitledBorder.LEFT);
        jPanel2.setBorder(vienBorder);
    }
public void veborderpenal3()
    {
        Border mauBorder=BorderFactory.createLineBorder(Color.red);
        TitledBorder vienBorder= BorderFactory.createTitledBorder(mauBorder);
        vienBorder.setTitleJustification(TitledBorder.LEFT);
        jPanel3.setBorder(vienBorder);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai86.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai86.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai86.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai86.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Bai86 n =new Bai86();
                n.veborderpenal1();
                n.veborderpenal2();
                n.veborderpenal3();
                n.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbotoden;
    private javax.swing.JButton btnnhap;
    private javax.swing.JButton btntodensochan;
    private javax.swing.JButton btntodensole;
    private javax.swing.JButton btntodensonguyento;
    private javax.swing.JButton btntong;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
