/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bài69.bài80;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Bai90 extends javax.swing.JFrame {

    /**
     * Creates new form Bai90
     */
    public class Sinhvien
    {
        String mssv;
        String hoten;
        String malop;
        Double diemmon1;
        Double diemmon2;
        public Sinhvien(){}
        public Sinhvien(String a,String b,String c,Double d,Double e)
        {
            mssv=a;
            hoten=b;
            malop=c;
            diemmon1=d;
            diemmon2=e;
        }
        public String getmssv()
        {
            return mssv;
        }
        public String gethoten()
        {
            return hoten;
        }
        public String malop()
        {
            return malop;
        }
        public Double getdiemmon1()
        {
            return diemmon1;
        }
        public Double getdiemmon2()
        {
            return diemmon2;
        }
        public void setmssv(String a)
        {
            mssv=a;
        }
        public void sethoten(String a)
        {
            hoten=a;
        }
        public void setmalop(String a)
        {
            malop=a;
        }
        public void setdiemmon1(Double a)
        {
            diemmon1=a;
        }
        public void setdiemmon2(Double a)
        {
            diemmon2=a;
        }
        public double diemtb()
        {
            double kq;
            kq=(diemmon1+diemmon2)/2;
            return kq;
        }
        public String Ketqua()
        {
            if(diemtb()>=5)
                return "DAU";
            else return "ROT";
        }
        public String toString()
        {
            return mssv;
        }
    }
    public Bai90() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmssv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtdiem1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdiem2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdiemtb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtkq = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mã sinh viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Họ tên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Mã lớp");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "59CNTT1", "59CNTT2", "59CNTT3", "58CNTT2", "58CNTT1", "57CNTT1", "57CNTT2" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Điểm môn 1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Điểm môn 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Điểm trung bình");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Kết quả");

        jButton1.setText("Kết quả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Mã lớp", "Điểm môn 1", "Điểm môn 2", "Điểm trung bình", "Kết quả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtkq)
                    .addComponent(txtdiemtb)
                    .addComponent(txtdiem2)
                    .addComponent(txtdiem1)
                    .addComponent(jComboBox1, 0, 240, Short.MAX_VALUE)
                    .addComponent(txthoten)
                    .addComponent(txtmssv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Double.parseDouble(txtdiem1.getText());
            Double.parseDouble(txtdiem2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Điểm phải nhập số");
            txtdiem1.setText("");
                txtdiem2.setText("");
                txtdiem1.requestFocus();
        }
        Sinhvien sv=new Sinhvien(txtmssv.getText(),txthoten.getText(),jComboBox1.getSelectedItem().toString(),Double.valueOf(txtdiem1.getText()),Double.valueOf(txtdiem2.getText()));
        txtdiemtb.setText(String.valueOf(sv.diemtb()));
        txtkq.setText(String.valueOf(sv.Ketqua()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
         try {
            Double.parseDouble(txtdiem1.getText());
            Double.parseDouble(txtdiem2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Điểm phải nhập số");
            txtdiem1.setText("");
                txtdiem2.setText("");
                txtdiem1.requestFocus();
        }
        if(txtmssv.getText().isEmpty()||txthoten.getText().isEmpty()||txtdiem1.getText().isEmpty()||txtdiem2.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Dữ liệu chưa đầy đủ");
        else if(trungnhanvien())
            JOptionPane.showMessageDialog(this, "Mã sinh viên bị trùng");
        else{
        Object[] data=new Object[7];
        data[0]=txtmssv.getText();
        data[1]=txthoten.getText();
        data[2]=jComboBox1.getSelectedItem().toString();
        data[3]=txtdiem1.getText();
        data[4]=txtdiem2.getText();
        data[5]=txtdiemtb.getText();
        data[6]=txtkq.getText();
        model.addRow(data);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        txtmssv.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 0)));
        txthoten.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 1)));
        jComboBox1.setSelectedItem(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 2)));
        txtdiem1.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 3)));
        txtdiem2.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 4)));
        txtdiemtb.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 5)));
        txtkq.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 6)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn hàng để xóa");
        else {
        int n=JOptionPane.showConfirmDialog(this, "Bạn chắc chắn xóa?","Thông Báo",JOptionPane.OK_CANCEL_OPTION);
        if(n==JOptionPane.OK_OPTION)
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public Double ktraso(Double a)
    {
        boolean check=false;
        double n=0;
        while(!check)
        {
            try {
               n=a;
               check=true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Phải nhập số");
                txtdiem1.setText("");
                txtdiem2.setText("");
                txtdiem1.requestFocus();
            }
        }
        return n;
    }
     public boolean trungnhanvien()
    {
        for(int i=0;i<jTable1.getRowCount();i++)
            if(txtmssv.getText().equals(jTable1.getValueAt(i, 0)))
                return true;
            return false;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai90.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai90.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai90.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai90.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai90().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdiem1;
    private javax.swing.JTextField txtdiem2;
    private javax.swing.JTextField txtdiemtb;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtkq;
    private javax.swing.JTextField txtmssv;
    // End of variables declaration//GEN-END:variables
}
